require("will.options")
require("will.keymaps")
require("will.plugins")
require("will.colorscheme")
require("will.lualine")
require("will.mason")
require("will.handlers")
require("will.null-ls")
require("will.autopairs")
require("will.comment")
require("will.completions")
require("will.gitsigns")
require("will.telescope")
require("will.toggleterm")
require("will.treesitter")
require("will.nvim_tree")
require("will.dap")
require("will.dap-python")
--[[ require("will.bufferline") ]]
require("will.nvim-surround")
require("will.indentline")
require("will.alpha")
require("leap").add_default_mappings()
require("will.which-key")
require("will.lspsaga-config")
-- require("will.autotag-config")
